#!/bin/bash
# vim:set noexpandtab:

# Exit on command errors and treat unset variables as an error
set -u

source .fonctions	# Loads the generic functions usually used in the script
source /usr/share/yunohost/helpers # Source app helpers

# Get multi-instances specific variables
app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)

# Stop togetherjs service
if [ -e "/etc/systemd/system/togetherjs.service" ]; then
	echo "Delete systemd script"
	sudo systemctl stop togetherjs.service
	sudo systemctl disable togetherjs.service
	sudo rm "/etc/systemd/system/togetherjs.service"
	systemctl daemon-reload
fi

# Remove monitoring service Yunohost.
if sudo yunohost service status | grep -q togetherjs	# Test the existence of the service in Yunohost
then
	echo "Remove togetherjs service"
	sudo yunohost service remove togetherjs
fi

SECURE_REMOVE '/usr/local/bin/togetherjs.sh'

SECURE_REMOVE '/etc/nginx/conf.d/$domain.d/$app.conf'

SECURE_REMOVE '/var/log/$app/'	# Delete log

REMOVE_LOGROTATE_CONF	# Delete logrotate configuration

SECURE_REMOVE '/var/www/$app'	# Delete directory application

REMOVE_NGINX_CONF	# Delete nginx configuration

# Remove conf from framaestro
fm_path=$(ynh_app_setting_get 'framaestro' 'final_path')
sudo sed -i -e "s@^together = .*@//together = 'https://__TOGETHERJS__';@" $fm_path/p/config.js

# Reload SSOwat configuration
sudo yunohost app ssowatconf

echo -e "\e[0m"	# Restore normal color
